const LANG_TOKEN_NAME = 'LANG_TOKEN_NAME';
const REFRESH_TOKEN_NAME = 'REFRESH_TOKEN_NAME';
const ACCESS_TOKEN_NAME = 'ACCESS_TOKEN_NAME';

export { LANG_TOKEN_NAME, ACCESS_TOKEN_NAME, REFRESH_TOKEN_NAME };
